/**
*  SPDX-FileCopyrightText:  Copyright Hewlett Packard Enterprise Development LP
*  SPDX-License-Identifier:  MIT
**/

#include <stdio.h>
#include <string.h>

// Configure the input and output interfaces for the decompressor
#define FHD_INPUT_MEMORY
#define FHD_OUTPUT_MEMORY
// Define FHD_IMPLEMENTATION to generate the compressor code, not just
// declare the interface.
#define FHD_IMPLEMENTATION
#include "FlexHeatshrink.h"

// Sample data, generated by:
//   echo "hello world, how are hello world, you doing" | heatshrink -e -w 8 -l 4 | xxd -i
uint8_t
TestData[] = { 
  0xb4, 0x59, 0x6d, 0x96, 0xcb, 0x7c, 0x82, 0xef, 0x6f, 0xb9, 0x5b, 0x2c,
  0x92, 0xc9, 0x05, 0xa2, 0xdf, 0x77, 0x90, 0x58, 0x6e, 0x56, 0x50, 0x38,
  0x85, 0x2e, 0xf3, 0x6f, 0xba, 0xc8, 0x2c, 0x96, 0xfb, 0x4d, 0xba, 0xcf,
  0x0a
};

/**
  Sample program for memory-to-memory decompression

  This program decompresses the TestData[] array to a memory buffer, and prints
  the data to stdout.  It illustrates a common way to configure and use
  FlexHeatshrink.h.  See the full documentation in FlexHeatshrink.h.

  @param   Argc    Argument count (unused)
  @param   Argv    Argument list (unused)

  @return  Status  0 on success, or the error code returned by the decompressor

**/
int
main (
 int  Argc,
 char **Argv
 )
{
  int                       Status;
  uint8_t                   OutputBuffer[256]; // Must be at least 1<<windowsize 
  fhd_context_memory_memory Context;

  // Ensure output is NUL-terminated
  memset (OutputBuffer, 0, sizeof (OutputBuffer));

  // Initialize the context structure.  After zeroing it, set the fields
  // relevant to the selected FHD_INPUT_* and FHD_OUTPUT_* settings.
  memset (&Context, 0, sizeof (Context));
  Context.InputBuffer  = TestData;
  Context.InputLen     = sizeof(TestData);
  Context.OutputBuffer = OutputBuffer;
  Context.OutputLen    = sizeof(OutputBuffer);
  Context.WindowBits   = 8;
  Context.BackrefBits  = 4;

  // Decompress the input data to the output buffer
  Status = fhd_memory_memory (&Context);
  if (FHD_RET_SUCCESS != Status) {
    fprintf (stderr, "Error! Status: %d\n", Status);
    return Status;
  }

  puts (OutputBuffer);
  return 0;
}

