/**
*  SPDX-FileCopyrightText:  Copyright Hewlett Packard Enterprise Development LP
*  SPDX-License-Identifier:  MIT
**/

/* Test heatshrink decoder infrastructure */

#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdint.h>
#include <stdlib.h>

#define TRUE  (1 == 1)
#define FALSE (1 == 0)

// Forward declarations
typedef struct fhd_context_s_func_func fhd_context_func_func;
int InputFunc (fhd_context_func_func *ctx);
int OutputFunc (fhd_context_func_func *ctx, uint8_t byte);

typedef struct fhd_context_s_file fhd_context_file;
int ReadFile (fhd_context_file *ctx);
int WriteFile (fhd_context_file *ctx, uint8_t byte);

// Test input data.  Generated by:
// echo "hello world, how are hello world, you doing" | heatshrink -e -w 8 -l 4 | xxd -i
uint8_t TestData[] = { 
  0xb4, 0x59, 0x6d, 0x96, 0xcb, 0x7c, 0x82, 0xef, 0x6f, 0xb9, 0x5b, 0x2c,
  0x92, 0xc9, 0x05, 0xa2, 0xdf, 0x77, 0x90, 0x58, 0x6e, 0x56, 0x50, 0x38,
  0x85, 0x2e, 0xf3, 0x6f, 0xba, 0xc8, 0x2c, 0x96, 0xfb, 0x4d, 0xba, 0xcf,
  0x0a
};
const uint8_t *TestDataEnd = TestData + sizeof (TestData);

uint8_t *ExpectedData = "hello world, how are hello world, you doing\n";

// Buffer for holding output
uint8_t OutputBuffer[512];
const uint8_t *OutputBufferEnd = OutputBuffer + sizeof (OutputBuffer);


#define FHD_IMPLEMENTATION

// Memory to memory, with custom window and backref size
#define FHD_INPUT_MEMORY
#define FHD_OUTPUT_MEMORY
#define FHD_WINDOW_USER_OPAQUE  uint8_t  MyWindowBits;
#define FHD_BACKREF_USER_OPAQUE uint8_t  MyBackrefBits;
#define FHD_USER_WINDOW(C)  ((C)->MyWindowBits)
#define FHD_USER_BACKREF(C) ((C)->MyBackrefBits)
#include "FlexHeatshrink.h"
#undef FHD_INPUT_MEMORY
#undef FHD_OUTPUT_MEMORY
#undef FHD_WINDOW_USER_OPAQUE
#undef FHD_BACKREF_USER_OPAQUE
#undef FHD_USER_WINDOW
#undef FHD_USER_BACKREF

// Memory to getc, with a fixed window and backref size, declared "static"
#define FHD_INPUT_MEMORY
#define FHD_OUTPUT_GETC
#define FHD_FIXED_WINDOW 8
#define FHD_FIXED_BACKREF 4
#include "FlexHeatshrink.h"
#undef FHD_INPUT_MEMORY
#undef FHD_OUTPUT_GETC
#undef FHD_FIXED_WINDOW
#undef FHD_FIXED_BACKREF

// Input function to output function, with a user-supplied decorator
#define FHD_INPUT_FUNC(C)        InputFunc (C)
#define FHD_OUTPUT_FUNC(C, byte) OutputFunc (C, (byte))
#define FHD_OPAQUE                              \
  uint16_t InputPos;                            \
  uint16_t OutputPos;
#define FHD_USE_COROUTINE // So the functions can return temporary errors
#define FHD_DECORATOR static inline
#include "FlexHeatshrink.h"
#undef FHD_INPUT_FUNC
#undef FHD_OUTPUT_FUNC
#undef FHD_OPAQUE
#undef FHD_USE_COROUTINE
#undef FHD_DECORATOR

// Input buffer to output buffer, with a separate history buffer
#define FHD_INPUT_BUFFER
#define FHD_OUTPUT_BUFFER
#define FHD_HISTORY_USER_OPAQUE                 \
  uint8_t  *MyHistoryBuffer;                    \
  uint16_t MyHistoryBufferPlace;                \
  uint16_t MyHistoryBufferSize;
#define FHD_HISTORY_USER_GET(C, Index, Out)                     \
  do {                                                          \
    int BufferPlace;                                            \
    BufferPlace = (C)->MyHistoryBufferPlace - (Index);          \
    if (BufferPlace < 0 )                                       \
      BufferPlace += (C)->MyHistoryBufferSize;                  \
    if (BufferPlace < 0 )                                       \
      return -9; /* corrupt input.  assert failure? */          \
    (Out) = (C)->MyHistoryBuffer[BufferPlace];                  \
  } while (0)
#define FHD_HISTORY_USER_ADD(C, Byte)                                   \
  do {                                                                  \
    (C)->MyHistoryBuffer[(C)->MyHistoryBufferPlace++] = Byte;           \
    if ((C)->MyHistoryBufferPlace >= (C)->MyHistoryBufferSize) {        \
      (C)->MyHistoryBufferPlace = 0;                                    \
    }                                                                   \
  } while (0)
#include "FlexHeatshrink.h"
#undef FHD_INPUT_BUFFER
#undef FHD_OUTPUT_BUFFER
#undef FHD_HISTORY_USER_OPAQUE
#undef FHD_HISTORY_USER_GET
#undef FHD_HISTORY_USER_ADD

// Putc to memory
#define FHD_INPUT_PUTC
#define FHD_OUTPUT_MEMORY
#include "FlexHeatshrink.h"
#undef FHD_INPUT_PUTC
#undef FHD_OUTPUT_MEMORY

// Custom input and output, with a custom name and limited backref size.
// Based on the "memory" configurations, with hardcoded buffers.

#define FHD_INPUT_CUSTOM
#define FHD_INT_INPUT_OPAQUE \
  int InputPos;
#define FHD_INT_GET_BYTE(C, Byte)               \
  do {                                          \
    if ((C)->InputPos >= sizeof (TestData)) {   \
      return FHD_RET_SUCCESS;                   \
    }                                           \
    (Byte) = TestData[(C)->InputPos++];         \
  } while (0)

#define FHD_OUTPUT_CUSTOM
#define FHD_INT_OUTPUT_OPAQUE \
  int OutputPos;
#define FHD_INT_PUT_BYTE(C, Byte)                       \
  do {                                                  \
    if ((C)->OutputPos >= sizeof (OutputBuffer)) {      \
      return FHD_RET_OVERFLOW;                          \
    }                                                   \
    OutputBuffer[(C)->OutputPos++] = (Byte);            \
  } while (0)
#define FHD_MAX_WINDOW 8
#define FHD_INT_NAME(Name) my_ ## Name
#include "FlexHeatshrink.h"
#undef FHD_INPUT_CUSTOM
#undef FHD_OUTPUT_CUSTOM
#undef FHD_MAX_WINDOW

// File to file, for the gcc example.  With fixed numbers of window and
// backref bits, and a custom name.
#define FHD_INPUT_FUNC(C) ReadFile (C)
#define FHD_OUTPUT_FUNC(C, Byte) WriteFile (C, (Byte))
#define FHD_FIXED_WINDOW  9
#define FHD_FIXED_BACKREF 5
#define FHD_INT_NAME(Name) Name ## _file
#define FHD_OPAQUE                              \
  FILE *InputFile;                              \
  FILE *OutputFile;
#include "FlexHeatshrink.h"
#undef FHD_INPUT_FUNC
#undef FHD_OUTPUT_FUNC
#undef FHD_FIXED_WINDOW
#undef FHD_FIXED_BACKREF
#undef FHD_INT_NAME
#undef FHD_OPAQUE

// arbitrary negative error values
#define INFUNC_ERR  -10
#define OUTFUNC_ERR -11

/**
  Input function that returns test data bytes with simulated errors

  This function provides input bytes from TestData[] to the decompressor,
  simulating occasional errors every 10th call to test error handling. It
  tracks the current position in the input buffer and returns FHD_RET_END_OF_INPUT
  when all data has been consumed.

  @param   Context  Pointer to the function-to-function decompression context

  @return  Byte                  The next input byte (0-255) on success
  @return  INFUNC_ERR            Simulated error condition (every 10th call)
  @return  FHD_RET_END_OF_INPUT  All input data has been consumed

**/
int
InputFunc (
  fhd_context_func_func *Context
  )
{
  static int Count = 0;

  if ((Count++ % 10) == 0) {
    return INFUNC_ERR;
  }
  if (Context->InputPos >= sizeof (TestData)) {
    return FHD_RET_END_OF_INPUT;
  }
  return TestData[Context->InputPos++];
}

/**
  Output function that accepts decompressed bytes with simulated errors

  This function receives output bytes from the decompressor and stores them in
  OutputBuffer[], simulating occasional errors every 10th call to test error
  handling. It checks for buffer overflow and returns appropriate error codes.

  @param   Context  Pointer to the function-to-function decompression context
  @param   Byte     The decompressed byte to write to the output buffer

  @return  FHD_RET_SUCCESS  Byte successfully written to output buffer
  @return  OUTFUNC_ERR      Simulated error condition (every 10th call)
  @return  FHD_RET_OVERFLOW Output buffer is full

**/
int
OutputFunc (
  fhd_context_func_func *Context,
  uint8_t                Byte
  )
{
  static int Count = 0;

  if ((Count++ % 10) == 0) {
    return OUTFUNC_ERR;
  }
  if (Context->OutputPos >= sizeof (OutputBuffer)) {
    return FHD_RET_OVERFLOW;
  }
  OutputBuffer[Context->OutputPos++] = Byte;
  return FHD_RET_SUCCESS;
}

/**
  Read an input byte from a file

  This function reads a single byte from the input file specified in the
  context structure. It is used as a custom input function for file-to-file
  decompression operations.

  @param   Context  Pointer to the decompression context containing the input file

  @return  Byte                  The next input byte (0-255) on successful read
  @return  FHD_RET_END_OF_INPUT  End of file reached or read error occurred

**/
int
ReadFile (
  fhd_context_file *Context
  )
{
  char Byte;

  Byte = 0;
  if (fread (&Byte, 1, 1, Context->InputFile) == 1) {
    return (unsigned)Byte & 0xff;
  }

  return FHD_RET_END_OF_INPUT;
}

/**
  Write an output byte to a file

  This function writes a single decompressed byte to the output file specified
  in the context structure. It is used as a custom output function for 
  file-to-file decompression operations.

  @param   Context  Pointer to the decompression context containing the output file
  @param   Byte     The decompressed byte to write to the output file

  @return  FHD_RET_SUCCESS  Byte successfully written to file
  @return  OUTFUNC_ERR      Write error occurred

**/
int
WriteFile (
  fhd_context_file *Context,
  uint8_t           Byte
  )
{
  if (fwrite (&Byte, 1, 1, Context->OutputFile) != 1) {
    return OUTFUNC_ERR;
  }

  return FHD_RET_SUCCESS;
}

/**
  Verify decompressed output matches expected data

  This function compares the decompressed output data against the expected
  result (ExpectedData) to validate correct decompression. It checks both
  the length and byte-by-byte content, printing diagnostic messages for
  any mismatches found.

  @param   Data     Pointer to the decompressed output data to verify
  @param   DataLen  Length of the output data, or 0 to auto-detect with strnlen

  @return  TRUE   Output data matches expected data
  @return  FALSE  Output data length or content does not match expected data

**/
int
CheckOutput (
  uint8_t *Data,
  int     DataLen
  )
{
  int Index;
  int ExpectedLen;

  if (0 == DataLen) {
    DataLen = strnlen (Data, sizeof (OutputBuffer));
  }
  ExpectedLen = strlen (ExpectedData);

  if (DataLen != ExpectedLen) {
    printf ("  Bad length: in (%d) != out (%d)\n", ExpectedLen, DataLen);
    return FALSE;
  }

  for (Index = 0; Index < DataLen; Index++) {
    if (ExpectedData[Index] != Data[Index]) {
      printf ("  Miscompare: in[%d]=0x%x, out[%d]=0x%x\n",
              Index, ExpectedData[Index], Index, Data[Index]);
      return FALSE;
    }
  }

  if (Index >= DataLen) {
    printf ("  Match!\n");
  }

  return TRUE;
}

/**
  Test program for Flexible Heatshrink Decoder infrastructure

  This program exercises various decompression configurations to test the
  Flexible Heatshrink Decoder library. It runs multiple test cases using different
  input/output methods and validates that all decompression operations produce the
  expected output.  It attempts test all customization options provided by the library.

  @param   Argc  Argument count (unused)
  @param   Argv  Argument list (unused)

  @return  0  All tests passed successfully
  @return  1  One or more tests failed

**/
int
main (
  int  Argc,
  char **Argv
  )
{
  int Status;
  int Result;

  Result = TRUE;

  //----------------------

  {
    fhd_context_memory_memory Context;

    printf ("memory->memory\n");
    memset (&Context, 0, sizeof (Context));
    memset (OutputBuffer, 0, sizeof (OutputBuffer));
    Context.InputBuffer = TestData;
    Context.InputLen = sizeof (TestData);
    Context.OutputBuffer = OutputBuffer;
    Context.OutputLen = sizeof (OutputBuffer);
    Context.MyWindowBits = 8;
    Context.MyBackrefBits = 4;

    Status = fhd_memory_memory (&Context);
    if (FHD_RET_SUCCESS != Status) {
      printf ("Status: %d\n", Status);
    }
    printf ("Output: %s\n", OutputBuffer);
    Result &= CheckOutput (OutputBuffer, 0);
  }

  //----------------------

  {
    fhd_context_memory_getc Context;
    int                     ExpectedIndex;

    printf ("\nmemory->getc\n");
    memset (&Context, 0, sizeof (Context));
    Context.InputBuffer = TestData;
    Context.InputLen = sizeof (TestData);

    printf ("Output: ");
    ExpectedIndex = 0;
    while (1) {
      Status = fhd_memory_getc (&Context);
      if (Status < 0) {
        break;
      }
      if (ExpectedData[ExpectedIndex++] != Status) {
        printf ("\n  Mismatch at %d, expected %d, got %d\n", ExpectedIndex, ExpectedData[ExpectedIndex], Status);
        break;
      }
      putc (Status, stdout);
    }
    printf ("\n");
    if (FHD_RET_SUCCESS == Status) {
      printf ("  Match!\n");
    }
    else {
      printf ("Status: %d\n", Status);
    }
  }

  //----------------------

  {
    fhd_context_func_func ctx_f_f;

    printf ("function->function\n");
    memset (&ctx_f_f, 0, sizeof (ctx_f_f));
    memset (OutputBuffer, 0, sizeof (OutputBuffer));
    ctx_f_f.WindowBits = 8;
    ctx_f_f.BackrefBits = 4;

    while (1) {
      Status = fhd_func_func (&ctx_f_f);
      if (INFUNC_ERR == Status || OUTFUNC_ERR == Status) {
        printf ("  progress: %d\n", Status);
        continue;
      }
      break;
    }
    if (FHD_RET_END_OF_INPUT != Status) {
      printf ("Status: %d\n", Status);
    }
    printf ("Output: %s\n", OutputBuffer);
    Result &= CheckOutput (OutputBuffer, 0);
  }

  //----------------------

  {
    fhd_context_buffer_buffer Context;

    printf ("buffer->buffer\n");
    memset (&Context, 0, sizeof (Context));
    memset (OutputBuffer, 0, sizeof (OutputBuffer));

    Context.WindowBits = 8;
    Context.BackrefBits = 4;

    Context.MyHistoryBufferSize = 1 << Context.WindowBits;
    Context.MyHistoryBuffer = malloc (Context.MyHistoryBufferSize);
    if (NULL == Context.MyHistoryBuffer) {
      perror ("Failed to allocate history buffer");
      exit (1);
    }
    memset (Context.MyHistoryBuffer, 0, Context.MyHistoryBufferSize);

    // Read the input in pieces, generate the output in pieces
    #define IN_QUANT  10
    #define OUT_QUANT 8
    // To test end cases:
    //#define IN_QUANT  1
    //#define OUT_QUANT 1
    //#define IN_QUANT  sizeof (TestData)
    //#define OUT_QUANT sizeof (OutputBuffer)
    Context.InputBuffer  = TestData;
    Context.InputLen     = IN_QUANT;
    Context.OutputBuffer = OutputBuffer;
    Context.OutputLen    = OUT_QUANT;

    while (Context.InputBuffer < TestDataEnd) {
      Status = fhd_buffer_buffer (&Context);
      if (Status == FHD_RET_END_OF_INPUT) { // Input buffer empty
        printf ("  progress: %d\n", Status);
        Context.InputBuffer += IN_QUANT;
        if (Context.InputBuffer >= TestDataEnd) {
          break;
        }
        Context.InputLen = TestDataEnd - Context.InputBuffer;
        if (Context.InputLen > IN_QUANT) {
          Context.InputLen = IN_QUANT;
        }
        Context.InputPlace = 0;
      }
      else if (Status == FHD_RET_OVERFLOW) {  // Output buffer full
        printf ("  progress: %d\n", Status);
        Context.OutputBuffer += OUT_QUANT;
        if (Context.OutputBuffer >= OutputBufferEnd) { // shouldn't happen
          printf ("Error: output buffer overflow\n");
        }
        Context.OutputLen = OutputBufferEnd - Context.OutputBuffer;
        if (Context.OutputLen > OUT_QUANT) {
          Context.OutputLen = OUT_QUANT;
        }
        Context.OutputPlace = 0;
      }
      else {
        printf ("Status: %d\n", Status); // Unexpected
        break;
      }
    }
    printf ("Output: %s\n", OutputBuffer);
    Result &= CheckOutput (OutputBuffer, 0);
    free (Context.MyHistoryBuffer);
  }

  //----------------------

  {
    fhd_context_putc_memory Context;
    int                     Index;

    printf ("putc->memory\n");
    memset (&Context, 0, sizeof (Context));
    memset (OutputBuffer, 0, sizeof (OutputBuffer));
    Context.OutputBuffer = OutputBuffer;
    Context.OutputLen = sizeof (OutputBuffer);
    Context.WindowBits = 8;
    Context.BackrefBits = 4;
    Status = fhd_putc_memory (&Context); // First InputByte is ignored
    if (FHD_RET_END_OF_INPUT != Status) {
      printf ("Status: %d\n", Status);
    }

    for (Index = 0; Index < sizeof (TestData); Index++) {
      Context.InputByte = TestData[Index];
      Status = fhd_putc_memory (&Context);
      if (FHD_RET_END_OF_INPUT != Status) {
        printf ("Status: %d\n", Status);
        break;
      }
    }
    printf ("Output: %s\n", OutputBuffer);
    Result &= CheckOutput (OutputBuffer, 0);
  }

  //----------------------

  {
    my_fhd_context Context;

    printf ("custom->custom\n");
    memset (&Context, 0, sizeof (Context));
    memset (OutputBuffer, 0, sizeof (OutputBuffer));
    Context.WindowBits = 8;
    Context.BackrefBits = 4;
    Status = my_fhd (&Context);
    if (FHD_RET_SUCCESS != Status) {
      printf ("Status: %d\n", Status);
    }
    printf ("Output: %s\n", OutputBuffer);
    Result &= CheckOutput (OutputBuffer, 0);
  }

  //----------------------

  {
    fhd_context_file Context;

    printf ("file->file\n");
    memset (&Context, 0, sizeof (Context));
    Context.InputFile = fopen ("gcc.hs", "rb");
    if (Context.InputFile == NULL) {
      perror ("Error: can't open input file gcc.hs");
      return -1;
    }
    Context.OutputFile = fopen ("gcc.check", "wb");
    if (Context.OutputFile == NULL) {
      perror ("Error: can't open output file gcc.check");
      return -1;
    }
    Status = fhd_file (&Context);
    if (FHD_RET_END_OF_INPUT != Status) {
      printf ("Status: %d\n", Status);
    }
    printf ("Output in gcc.check\n");
  }

  //----------------------

  if (Result) {
    printf ("All tests passed!\n");
    return 0;
  }
  else {
    printf ("Some test(s) failed, see output above\n");
    return 1;
  }
}
